#!/usr/bin/env node
// contracts/out -> web/src/abi.ts, typed `as const` so viem/wagmi infer every argument and return.
import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("..", import.meta.url).pathname;
const contracts = {
  blueFundAbi: "BlueFund.sol/BlueFund.json",
  chipBurnerAbi: "ChipBurner.sol/ChipBurner.json",
  chipAbi: "IChip.sol/IChip.json",
  mockStockAbi: "MockStock.sol/MockStock.json",
  mockChipAbi: "MockChip.sol/MockChip.json",
  mockFaucetAbi: "MockBasketFaucet.sol/MockBasketFaucet.json",
};

let out = "// Generated by scripts/export-abi.mjs from contracts/out. Do not edit.\n";
for (const [name, file] of Object.entries(contracts)) {
  const { abi } = JSON.parse(readFileSync(`${root}contracts/out/${file}`, "utf8"));
  out += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync(`${root}web/src/abi.ts`, out);
console.log(`wrote web/src/abi.ts (${Object.keys(contracts).join(", ")})`);
